//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTypeInfo
    {
        public string AccountType { get; set; }
        public string TypeDescription { get; set; }
        public string TypeLevel { get; set; }
        public string FirstLevel { get; set; }
        public string SecondLevel { get; set; }
        public string ThirdLevel { get; set; }
        public string FourthLevel { get; set; }
        public string FifthLevel { get; set; }
        public string ModuleCode { get; set; }
        public int LastNo { get; set; }
        public string GLCode { get; set; }
        public string UserId { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
