//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInformation
    {
        public List<AccountInformation> AccountInfoTrees = new List<AccountInformation>();

        public AccountInformation()
        {
            AccountInfoTrees = new List<AccountInformation>();
        }
        public long AccountInformationIdentity { get; set; }
        public string BankCode { get; set; }
        public string AccountCode { get; set; }
        public string AccountHead { get; set; }
        public long Category { get; set; }
        public long AccountStatusCode { get; set; }
        public string AccountLevel { get; set; }
        public string FirstLevel { get; set; }
        public string SecondLevel { get; set; }
        public string ThirdLevel { get; set; }
        public string FourthLevel { get; set; }
        public string FifthLevel { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
