//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovedRefitDockingSchedule
    {
        public long ParentCode { get; set; }
        public long id { get; set; }
        public string Name { get; set; }
        public System.DateTime LastRefitForm { get; set; }
        public System.DateTime LastRefitTo { get; set; }
        public System.DateTime LastDockingForm { get; set; }
        public System.DateTime LastDockingTo { get; set; }
        public int LEVEL { get; set; }
        public int firstLevel { get; set; }
        public long SecendLevel { get; set; }
        public long ThirdLevel { get; set; }
    }
}
