//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonCode1
    {
        public CommonCode1()
        {
            this.ControlShipInfoes = new HashSet<ControlShipInfo>();
            this.DeckInfoes = new HashSet<DeckInfo>();
            
            this.Documentations = new HashSet<Documentation>();
            this.FortnightlyInfoes = new HashSet<FortnightlyInfo>();
            this.LubOilConsumptions = new HashSet<LubOilConsumption>();
            this.MachineryRunningInfoes = new HashSet<MachineryRunningInfo>();
            this.MachineryRunningInfoes1 = new HashSet<MachineryRunningInfo>();
            this.MessageInfoes = new HashSet<MessageInfo>();
            this.ProcurementSchedules = new HashSet<ProcurementSchedule>();
            this.ShipDetails = new HashSet<ShipDetail>();
            this.ShipInactives = new HashSet<ShipInactive>();
            this.ShipInactiveOrgs = new HashSet<ShipInactiveOrg>();
            this.ShipInfoes = new HashSet<ShipInfo>();
            this.ShipInfoes1 = new HashSet<ShipInfo>();
            this.ShipInfoes2 = new HashSet<ShipInfo>();
            this.TrainingInfoes = new HashSet<TrainingInfo>();
            this.TrainingInfoes1 = new HashSet<TrainingInfo>();
        }

        public long CommonCodeID { get; set; }
        public string BankCode { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public string TypeValue { get; set; }
        public string BTypeValue { get; set; }
        public string AdditonalValue { get; set; }
        public string DisplayCode { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
      
        public virtual ICollection<ControlShipInfo> ControlShipInfoes { get; set; }
       
        public virtual ICollection<DeckInfo> DeckInfoes { get; set; }
         public virtual ICollection<Documentation> Documentations { get; set; }
       
        public virtual ICollection<FortnightlyInfo> FortnightlyInfoes { get; set; }
        
        public virtual ICollection<LubOilConsumption> LubOilConsumptions { get; set; }
        
        public virtual ICollection<MachineryRunningInfo> MachineryRunningInfoes { get; set; }
        
        public virtual ICollection<MachineryRunningInfo> MachineryRunningInfoes1 { get; set; }
        
        public virtual ICollection<MessageInfo> MessageInfoes { get; set; }
       
        public virtual ICollection<ProcurementSchedule> ProcurementSchedules { get; set; }
        
        public virtual ICollection<ShipDetail> ShipDetails { get; set; }
       
        public virtual ICollection<ShipInactive> ShipInactives { get; set; }
        
        public virtual ICollection<ShipInactiveOrg> ShipInactiveOrgs { get; set; }
        
        public virtual ICollection<ShipInfo> ShipInfoes { get; set; }
       
        public virtual ICollection<ShipInfo> ShipInfoes1 { get; set; }
       
        public virtual ICollection<ShipInfo> ShipInfoes2 { get; set; }
       
        public virtual ICollection<TrainingInfo> TrainingInfoes { get; set; }
        public virtual ICollection<TrainingInfo> TrainingInfoes1 { get; set; }

 
    }
}
