//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeckInfo:ReportHeader
    {
        public long DeckInfoIdentity { get; set; }

        public long ControlShipInfoId { get; set; }
        public Nullable<System.DateTime> ReportDateFrom { get; set; }
        public Nullable<System.DateTime> ReportDateTo { get; set; }
        public long HullStatus { get; set; }
        public string DechNo { get; set; }
        public string Compartment { get; set; }
        public string Location { get; set; }
        public System.DateTime CheckDate { get; set; }
        public string StatePlates { get; set; }
        public string StateFrames { get; set; }
        public string StateRivets { get; set; }
        public string StateCement { get; set; }
        public string PaintDescriptio { get; set; }
        public string PaintState { get; set; }
        public string SanctionDisLineW { get; set; }
        public string SanctionDisLineS { get; set; }
        public string SanctDisNonRW { get; set; }
        public string SanctDisNonRS { get; set; }
        public string HeadCoverWT { get; set; }
        public string HeadCoverS { get; set; }
        public string DefectDes { get; set; }
        public string DefectActionTaken { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateLastUpdate { get; set; }
        public string UserID { get; set; }
        public System.DateTime LastUpdate { get; set; }

        public virtual CommonCode CommonCode { get; set; }
        public virtual ControlShipInfo ControlShipInfo { get; set; }

        //report
        public string ShipName { get; set; }
    }
}
