//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelConsumption
    {
        public long FuelConsumptionIdentity { get; set; }
        public long ShipId { get; set; }
        public long Machinery { get; set; }
        public decimal? MachinaryOil { get; set; }
        public decimal LubOil { get; set; }
        public decimal HSDOil { get; set; }
        public decimal GreaseOil { get; set; }
        public decimal Water { get; set; }
        public decimal WLubOil { get; set; }

        public decimal PercentageOfOil { get; set; }
        public decimal AtSea { get; set; }
        public decimal Harbour { get; set; }
        public decimal RefGas { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string UserId { get; set; }
        public System.DateTime LastUpdate { get; set; }

        //public virtual CommonCode CommonCode { get; set; }
        public virtual ControlShipInfo ControlShipInfo { get; set; }
    }
}
