//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LubOilConsumption
    {
        public long LubOilConsumtionIdentity { get; set; }
        [Required]
        public long ShipId { get; set; }
        [Required]
        public long Machinery { get; set; }
        [Required]
        public long LubOilType { get; set; }
        [Required]
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public string Location { get; set; }
        public decimal RunningHour { get; set; }
        public decimal Price { get; set; }
        public string Unit { get; set; }
        public decimal Quantity { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }

        public virtual CommonCode CommonCode { get; set; }
        public virtual ControlShipInfo ControlShipInfo { get; set; }
    }
}
