//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineryRunningInfo
    {
        public long MachineryRunningIdentity { get; set; }
        public long ShipId { get; set; }
        public long HourRunTime { get; set; }
        public Nullable<long> Type { get; set; }
        public Nullable<decimal> Hour { get; set; }
        public Nullable<decimal> Minute { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string UserId { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }

        public virtual CommonCode CommonCode { get; set; }
        public virtual CommonCode CommonCode1 { get; set; }
        public virtual ControlShipInfo ControlShipInfo { get; set; }
    }
}
