//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEInfo
    {
        public Nullable<long> ShipId { get; set; }
        public decimal ParentCode { get; set; }
        public decimal ControlCode { get; set; }
        public string ControlName { get; set; }
        public string GenInfo { get; set; }
        public string Shafting { get; set; }
        public string MainThrusrShaft { get; set; }
        public string MiddleShaft { get; set; }
        public string AuxiliaryShaft { get; set; }
        public string PropellerShaft { get; set; }
        public string ControlValue { get; set; }
        public string AdditionalValue { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ControlLevel { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string Level1 { get; set; }
        public string Level2 { get; set; }
        public string Level3 { get; set; }
        public string Level4 { get; set; }
        public string Level5 { get; set; }
        public string ShipName { get; set; }
        public string Genaralgroup { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<decimal> EnduranceHr { get; set; }
        public Nullable<decimal> EnduranceNm { get; set; }
        public Nullable<decimal> ShaftSpeed { get; set; }
        public Nullable<decimal> Power { get; set; }
        public Nullable<decimal> FuelConsumption { get; set; }
        public string stDescription { get; set; }
        public Nullable<decimal> PortSpeed { get; set; }
        public Nullable<decimal> StableSpeed { get; set; }
        public Nullable<decimal> StbdSpeed { get; set; }
    }
}
