//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageInfoView
    {
        public long MessageInfoIdentity { get; set; }
        public System.DateTime MessageFromDate { get; set; }
        public Nullable<System.DateTime> MessageToDate { get; set; }
        public string Message { get; set; }
        public bool MessageForAll { get; set; }
        public int MessageFor { get; set; }
        public string Remark { get; set; }
        public string UserId { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }

        public string MsgToName { get; set; }
        public string MsgCC { get; set; }



        public virtual Role Role { get; set; }
       
    }
}
