//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipDetail
    {
        public long ShipDetailsIdentity { get; set; }
        [Required]
        public long ShipId { get; set; }
        [Required]
        public Nullable<long> SpecificationType { get; set; }
        [Required]
        public string Specification { get; set; }
        public string SpecificationValue { get; set; }
        public string AdditionalValue { get; set; }
        public string Remarks { get; set; }
        public string UserId { get; set; }
        public System.DateTime LastUpdate { get; set; }

        public virtual CommonCode CommonCode { get; set; }
        public virtual ControlShipInfo ControlShipInfo { get; set; }
    }
}
