//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipSpeedTrial
    {
        public long ShipSpeedTrialIdentity { get; set; }
        public long ShipId { get; set; }
        public string Description { get; set; }
        public decimal? PortSpeed { get; set; }
        public decimal? StbdSpeed { get; set; }
        public decimal? StableSpeed { get; set; }
        public string Remarks { get; set; }
        public string UserId { get; set; }
        public System.DateTime Lastupdate { get; set; }
        public Nullable<long> ControlShipInfoId { get; set; }

        public virtual ControlShipInfo ControlShipInfo { get; set; }

      
    }
}
