//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipInfo
    {

        public ShipInfo()
        {
            this.ShipInactiveOrgs = new HashSet<ShipInactiveOrg>();
            this.MonthlyReturns = new HashSet<MonthlyReturn>();
        }

        public long ShipInfoIdentity { get; set; }
        public string ShipId { get; set; }
        public long ControlShipInfoId { get; set; }
        public string ShipName { get; set; }
        public Nullable<long> SQD { get; set; }
        public Nullable<byte> RefitInterval { get; set; }
        public long RefitIntervalType { get; set; }
        public Nullable<byte> RefitDuration { get; set; }
        public long RefitDurationType { get; set; }
        public Nullable<byte> DockingDuration { get; set; }
        public long DockingDurationType { get; set; }
        public Nullable<System.DateTime> LastRefitDate { get; set; }
        public Nullable<System.DateTime> LastDockingDate { get; set; }
        public Nullable<System.DateTime> NextRefitDate { get; set; }
        public Nullable<System.DateTime> NextDockingDate { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Breadth { get; set; }
        public Nullable<decimal> DraughtAFT { get; set; }
        public Nullable<decimal> DraughtFWD { get; set; }
        public Nullable<decimal> Displacement { get; set; }
        public Nullable<byte> PropellerQty { get; set; }
        public Nullable<byte> RudderQty { get; set; }
        public Nullable<byte> SpeedMax { get; set; }
        public Nullable<byte> SpeedCont { get; set; }
        public Nullable<byte> SpeedEcon { get; set; }
        public Nullable<byte> SpeedMin { get; set; }
        public Nullable<decimal> TankCapacityFW { get; set; }
        public Nullable<decimal> TankCapacityFuel { get; set; }
        public Nullable<decimal> TankCapacityLuboil { get; set; }
        public string Remarks { get; set; }
        public string UserId { get; set; }
        public System.DateTime LastUpdate { get; set; }

        public virtual CommonCode CommonCode { get; set; }
        public virtual CommonCode CommonCode1 { get; set; }
        public virtual CommonCode CommonCode2 { get; set; }
        public virtual ControlShipInfo ControlShipInfo { get; set; }

        public virtual ICollection<ShipInactiveOrg> ShipInactiveOrgs { get; set; }

        public virtual ICollection<MonthlyReturn> MonthlyReturns { get; set; }
    }
}
