//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipEmployed:ReportHeader
    {
        public long EmployedIdentity { get; set; }
        public Nullable<long> ShipInfoIdentity { get; set; }
        [Required]
        public string Employment { get; set; }
        public Nullable<int> DaysFrom { get; set; }
        public Nullable<int> DaysTo { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        [Required]
        public string CompletionOfLast { get; set; }
        public string Date { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UserID { get; set; }
    
        public virtual ShipInfo ShipInfo { get; set; }
    }
}
