//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBankInfoMVC
    {
        public string CountryName { get; set; }
        public string BranchCode { get; set; }
        public string BankName { get; set; }
        public string DistrictName { get; set; }
        public string BranchName { get; set; }
        public string CountryCode { get; set; }
        public string CurrencyCode { get; set; }
        public string ZoneCode { get; set; }
        public string ZoneName { get; set; }
        public string BankCode { get; set; }
        public string SubBranchCode { get; set; }
        public string SubBranchName { get; set; }
        public string BrCode { get; set; }
        public string UserName { get; set; }
        public string UserFullName { get; set; }
        public decimal TransLimit { get; set; }
        public string LoweredRoleName { get; set; }
        public string NativeBranchCode { get; set; }
        public bool ApprovedUser { get; set; }
        public Nullable<int> AttemptCount { get; set; }
        public System.DateTime LastActivityDate { get; set; }
    }
}
