//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvGLTransaction
    {
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public string AccountCode { get; set; }
        public string VoucherNo { get; set; }
        public System.DateTime TransDate { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Currency { get; set; }
        public decimal ExchangeRate { get; set; }
        public Nullable<decimal> FDebit { get; set; }
        public Nullable<decimal> FCredit { get; set; }
        public string BranchCode { get; set; }
        public string AccountHead { get; set; }
        public string CategoryName { get; set; }
        public string AccountHead_1 { get; set; }
        public string AccountHead_2 { get; set; }
        public string AccountHead_3 { get; set; }
        public string AccountHead_4 { get; set; }
        public string AccountHead_5 { get; set; }
        public string AccountCode_1 { get; set; }
        public string AccountCode_2 { get; set; }
        public string Accountcode_3 { get; set; }
        public string AccountCode_4 { get; set; }
        public string AccountCode_5 { get; set; }
        public System.DateTime EndDate { get; set; }
        public string UserAgentBranch { get; set; }
        public string SubBranchCode { get; set; }
        public string SubBranchName { get; set; }
        public string AgentBranchName { get; set; }
    }
}
