//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAccountInfo
    {
        public string BankCode { get; set; }
        public string AccountCode { get; set; }
        public string AccountHead { get; set; }
        public string CategoryName { get; set; }
        public string AccountHead_1 { get; set; }
        public string AccountHead_2 { get; set; }
        public string AccountHead_3 { get; set; }
        public string AccountHead_4 { get; set; }
        public string AccountHead_5 { get; set; }
        public string AccountCode_1 { get; set; }
        public string AccountCode_2 { get; set; }
        public string Accountcode_3 { get; set; }
        public string AccountCode_4 { get; set; }
        public string AccountCode_5 { get; set; }
    }
}
