//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwICE:ReportHeader
        {
            public long IceId { get; set; }
            public long ControlShipInfoId { get; set; }
            public string InstructionNo { get; set; }
            public Nullable<System.DateTime> IceDate { get; set; }
            public string EngineManufacturer { get; set; }
            public string EngineModel { get; set; }
            public string EngineWork { get; set; }
            public string EngineSlNo { get; set; }
            public string EngineCoolingSys { get; set; }
            public string AfterRepairTime { get; set; }
            public string SinceCommission { get; set; }
            public string MaintenanceRemark { get; set; }
            public string EngineerRemark1 { get; set; }
            public string EngineerRemark2 { get; set; }
            public string EngineerRemark3 { get; set; }
            public string UserId { get; set; }
            public Nullable<System.DateTime> LastUpdate { get; set; }
            public Nullable<System.DateTime> todate { get; set; }
            public string BNS { get; set; }

            public virtual ControlShipInfo ControlShipInfo { get; set; }
    }
}
