//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwShipBankInfo
    {
        public long BranchInfoIdentity { get; set; }
        public string Code { get; set; }
        public Nullable<long> BankCodeIdentity { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public Nullable<long> DistrictCodeIdentity { get; set; }
        public string DistrictCode { get; set; }
        public string DistrictName { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public string BranchType { get; set; }
        public string BranchLevel { get; set; }
        public long ControlShipInfoId { get; set; }
        public decimal ParentCode { get; set; }
        public decimal ControlCode { get; set; }
        public string ControlName { get; set; }
        public string ControlValue { get; set; }
        public long SQD { get; set; }
        public string SQDName { get; set; }
        public Nullable<long> Organization { get; set; }
        public string ShipStatus { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<int> ControlLevel { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public int IsActive { get; set; }
        public Nullable<long> Level1 { get; set; }
    }
}
