//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwShipInfo:ReportHeader
    {
      



        public long ShipInfoIdentity { get; set; }
        public string ShipId { get; set; }
        public string ControlName { get; set; }
        public string CallSign { get; set; }
        public long ControlShipInfoId { get; set; }
        public string ShipName { get; set; }
        public string Organazation { get; set; }
        public string SQD { get; set; }
        public Nullable<byte> RefitInterval { get; set; }
        public string RefitIntervalType { get; set; }
        public Nullable<byte> RefitDuration { get; set; }
        public string RefitDurationType { get; set; }
        public Nullable<byte> DockingDuration { get; set; }
        public string DockingDurationType { get; set; }
        public Nullable<System.DateTime> LastRefitDate { get; set; }
        public Nullable<System.DateTime> LastDockingDate { get; set; }
        public Nullable<System.DateTime> NextRefitDate { get; set; }
        public Nullable<System.DateTime> NextDockingDate { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Breadth { get; set; }
        public Nullable<decimal> DraughtAFT { get; set; }
        public Nullable<decimal> DraughtFWD { get; set; }
        public Nullable<decimal> Displacement { get; set; }
        public Nullable<byte> PropellerQty { get; set; }
        public Nullable<byte> RudderQty { get; set; }
        public Nullable<byte> SpeedMax { get; set; }
        public Nullable<byte> SpeedCont { get; set; }
        public Nullable<byte> SpeedEcon { get; set; }
        public Nullable<byte> SpeedMin { get; set; }
        public Nullable<decimal> TankCapacityFW { get; set; }
        public Nullable<decimal> TankCapacityFuel { get; set; }
        public Nullable<decimal> TankCapacityLuboil { get; set; }
        public string Remarks { get; set; }
        public string UserId { get; set; }
        public System.DateTime LastUpdate { get; set; }

    }
}
