//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;

    public partial class vwShipcommOrgnaization : ReportHeader
    {
        public System.DateTime today { get; set; }
        public long ControlShipInfoId { get; set; }
        public Nullable<int> ControlLevel { get; set; }
        public Nullable<decimal> ParentCode { get; set; }
        public string ControlName { get; set; }
        public Nullable<long> statusCode { get; set; }
        public Nullable<long> Organization { get; set; }
        public string ORG { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TotalShip { get; set; }
        public Nullable<int> NonOpl { get; set; }
        public Nullable<int> Opl { get; set; }
    }
}
