//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneInfo
    {
        public ZoneInfo()
        {
            this.BranchInfoes = new HashSet<BranchInfo>();
            this.ShipAndDockings = new HashSet<ShipAndDocking>();
        }
    
        public long ZoneInfoIdentity { get; set; }
        public string ZoneCode { get; set; }
        public string ZoneName { get; set; }
        public string BankCode { get; set; }
    
        public virtual ICollection<BranchInfo> BranchInfoes { get; set; }
        public virtual ICollection<ShipAndDocking> ShipAndDockings { get; set; }
    }
}
