//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksAndBr
    {
        public long BooksAndBrIdentity { get; set; }
        public string BooksAndBrName { get; set; }
        public string UrlLink { get; set; }
        public string UserId { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
