//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageMachineriesInfo
    {
        public long MachineriesDescriptionIdentity { get; set; }
        public long ShipId { get; set; }
        public string SerialNo { get; set; }
        public Nullable<long> Description { get; set; }
        public Nullable<long> MobilityDescription { get; set; }
        public Nullable<System.DateTime> DamageDate { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string RepairTime { get; set; }
        public string Remarks { get; set; }
        public string MachineSerialNo { get; set; }
        public string MachineSide { get; set; }
        public Nullable<long> MachineName { get; set; }
        public string Hour { get; set; }
        public string Minute { get; set; }
        public string Duration { get; set; }
        public string MachineRemarks { get; set; }
        public string FuelSerialNo { get; set; }
        public Nullable<long> FuelOilId { get; set; }
        public Nullable<decimal> StockFuelOil { get; set; }
        public Nullable<decimal> FuelConsumption { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> ReceivedOil { get; set; }
        public Nullable<decimal> DonateOil { get; set; }
        public string UserId { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
    
        public virtual ControlShipInfo ControlShipInfo { get; set; }
        public virtual CommonCode CommonCode { get; set; }
        public virtual MachineryInfo MachineryInfo { get; set; }
        public virtual MachineryInfo MachineryInfo1 { get; set; }
    }
}
