//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefectMachinary
    {
        public long DefectMachinaryId { get; set; }
        public Nullable<long> MachineId { get; set; }
        public Nullable<long> MachinaryStatusId { get; set; }
        public Nullable<long> ShipId { get; set; }
        public Nullable<long> MonthlyReturnId { get; set; }
        public Nullable<System.DateTime> DefectDate { get; set; }
        public string DefectReasonDetail { get; set; }
        public string DefectSolution { get; set; }
        public string Remarks { get; set; }
    
        public virtual CommonCode CommonCode { get; set; }
        public virtual MonthlyReturn MonthlyReturn { get; set; }
        public virtual MachineryInfo MachineryInfo { get; set; }
    }
}
