//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentation
    {
        public long DocumentationIdentity { get; set; }
        public long ShipId { get; set; }
        public long DocumentType { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ImageUrl { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual ControlShipInfo ControlShipInfo { get; set; }
        public virtual CommonCode CommonCode { get; set; }
    }
}
