//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class FortnightlyInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FortnightlyInfo()
        {
            this.FortnightlyDetails = new HashSet<FortnightlyDetail>();
        }
    
        public int FortnightlyId { get; set; }
        public Nullable<long> CommonCodeID { get; set; }
        public long ShipInfoIdentity { get; set; }
        public string FortnightlyName { get; set; }
        public Nullable<System.DateTime> RefitDockSelectedStartDate { get; set; }
        public Nullable<System.DateTime> RefitDockSelectedEndDate { get; set; }
        public Nullable<System.DateTime> RefitStartDate { get; set; }
        public Nullable<System.DateTime> RefitEndDate { get; set; }
        public Nullable<System.DateTime> DockingDate { get; set; }
        public Nullable<System.DateTime> UnDockingDate { get; set; }
        public Nullable<int> ProgressTime { get; set; }
        public string TotalWorkProgress { get; set; }
        public string TotalWorkNo { get; set; }
        public string Progress25Percent { get; set; }
        public string Progress50Percent { get; set; }
        public string Progress75Percent { get; set; }
        public string Progress100Percent { get; set; }
        public string UnfishWork { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FortnightlyDetail> FortnightlyDetails { get; set; }
        public virtual ControlShipInfo ControlShipInfo { get; set; }
        public virtual CommonCode CommonCode { get; set; }
    }
}
