//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class FortNightly
    {
        public long FortNightlyIdentity { get; set; }
        public long ControlShipIdentity { get; set; }
        public Nullable<long> WorkCategoy { get; set; }
        public string WrNo { get; set; }
        public Nullable<long> DrType { get; set; }
        public string No { get; set; }
        public Nullable<System.DateTime> DrDate { get; set; }
        public string Description { get; set; }
        public Nullable<long> Docket { get; set; }
        public string PMH { get; set; }
        public Nullable<bool> TwentyFive { get; set; }
        public Nullable<System.DateTime> TwentyFiveDate { get; set; }
        public string TwentyFiveId { get; set; }
        public Nullable<bool> Fifty { get; set; }
        public Nullable<System.DateTime> FiftyDate { get; set; }
        public string FiftyId { get; set; }
        public Nullable<bool> SeventyFive { get; set; }
        public Nullable<System.DateTime> SeventyFiveDate { get; set; }
        public string SeventyFiveId { get; set; }
        public Nullable<bool> Complete { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public string CompleteId { get; set; }
        public string Remarks { get; set; }
        public string CreateId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LastUpdateId { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual ControlShipInfo ControlShipInfo { get; set; }
        public virtual CommonCode CommonCode { get; set; }
        public virtual CommonCode CommonCode1 { get; set; }
    }
}
