//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelConsumption
    {
        public long FuelConsumptionIdentity { get; set; }
        public long ShipId { get; set; }
        public long Machinery { get; set; }
        public Nullable<decimal> MachinaryOil { get; set; }
        public Nullable<decimal> LubOil { get; set; }
        public Nullable<decimal> HSDOil { get; set; }
        public Nullable<decimal> GreaseOil { get; set; }
        public Nullable<decimal> Water { get; set; }
        public Nullable<decimal> WLubOil { get; set; }
        public Nullable<decimal> PercentageOfOil { get; set; }
        public Nullable<decimal> AtSea { get; set; }
        public Nullable<decimal> Harbour { get; set; }
        public Nullable<decimal> RefGas { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string UserId { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual ControlShipInfo ControlShipInfo { get; set; }
    }
}
