//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetNotDoneMachinariesInfo
    {
        public string FormInfo { get; set; }
        public System.DateTime todate { get; set; }
        public string ReportName { get; set; }
        public long SInactiveIdentity { get; set; }
        public string ControlName { get; set; }
        public Nullable<long> ControlShipInfoId { get; set; }
        public string CrashDetails { get; set; }
        public System.DateTime InactiveDate { get; set; }
        public string Command { get; set; }
        public string Reference { get; set; }
        public string TakenStap { get; set; }
        public Nullable<bool> IsCompeleted { get; set; }
    }
}
