//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICE
    {
        public long IceId { get; set; }
        public long ControlShipInfoId { get; set; }
        public string InstructionNo { get; set; }
        public Nullable<System.DateTime> IceDate { get; set; }
        public string EngineManufacturer { get; set; }
        public string EngineModel { get; set; }
        public string EngineWork { get; set; }
        public string EngineSlNo { get; set; }
        public string EngineCoolingSys { get; set; }
        public string AfterRepairTime { get; set; }
        public string SinceCommission { get; set; }
        public string MaintenanceRemark { get; set; }
        public string EngineSlNo1 { get; set; }
        public string EngineCoolingSys1 { get; set; }
        public string AfterRepairTime1 { get; set; }
        public string SinceCommission1 { get; set; }
        public string MaintenanceRemark1 { get; set; }
        public string EngineSlNo2 { get; set; }
        public string EngineCoolingSys2 { get; set; }
        public string AfterRepairTime2 { get; set; }
        public string SinceCommission2 { get; set; }
        public string MaintenanceRemark2 { get; set; }
        public string EngineSlNo3 { get; set; }
        public string EngineCoolingSys3 { get; set; }
        public string AfterRepairTime3 { get; set; }
        public string SinceCommission3 { get; set; }
        public string MaintenanceRemark3 { get; set; }
        public string EngineerRemark1 { get; set; }
        public string EngineerRemark2 { get; set; }
        public string EngineerRemark3 { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<long> ICEFor { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual CommonCode CommonCode { get; set; }
        public virtual ControlShipInfo ControlShipInfo { get; set; }
    }
}
