//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachinaryRunningHour
    {
        public long MachinaryRunningHourId { get; set; }
        public Nullable<long> MonthlyReturnId { get; set; }
        public Nullable<long> NoOPSMachineId { get; set; }
        public Nullable<long> ShipId { get; set; }
        public Nullable<int> RunningHr { get; set; }
        public Nullable<int> RunningMin { get; set; }
    
        public virtual MonthlyReturn MonthlyReturn { get; set; }
        public virtual MachineryInfo MachineryInfo { get; set; }
    }
}
