//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageInfo
    {
        public long MessageInfoIdentity { get; set; }
        public System.DateTime MessageFromDate { get; set; }
        public Nullable<System.DateTime> MessageToDate { get; set; }
        public string Message { get; set; }
        public int MessageFor { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }
        public string UserId { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
