//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DNEEntities : DbContext
    {
        public DNEEntities()
            : base("name=DNEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountInformation> AccountInformations { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BooksAndBr> BooksAndBrs { get; set; }
        public virtual DbSet<DailyTransaction> DailyTransactions { get; set; }
        public virtual DbSet<DamageMachineriesInfo> DamageMachineriesInfoes { get; set; }
        public virtual DbSet<DeckInfo> DeckInfoes { get; set; }
        public virtual DbSet<DefectMachinary> DefectMachinaries { get; set; }
        public virtual DbSet<Documentation> Documentations { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
        public virtual DbSet<FortNightly> FortNightlies { get; set; }
        public virtual DbSet<FortnightlyDetail> FortnightlyDetails { get; set; }
        public virtual DbSet<FortnightlyInfo> FortnightlyInfoes { get; set; }
        public virtual DbSet<FuelConsumption> FuelConsumptions { get; set; }
        public virtual DbSet<LubOilConsumption> LubOilConsumptions { get; set; }
        public virtual DbSet<MachinaryRunningHour> MachinaryRunningHours { get; set; }
        public virtual DbSet<MachineryRunningInfo> MachineryRunningInfoes { get; set; }
        public virtual DbSet<MajorDemandOrProcure> MajorDemandOrProcures { get; set; }
        public virtual DbSet<OilRate> OilRates { get; set; }
        public virtual DbSet<POLExpenseInfo> POLExpenseInfoes { get; set; }
        public virtual DbSet<ProcurementSchedule> ProcurementSchedules { get; set; }
        public virtual DbSet<RefitDockingDefectList> RefitDockingDefectLists { get; set; }
        public virtual DbSet<Reporting> Reportings { get; set; }
        public virtual DbSet<RunningHourInfo> RunningHourInfoes { get; set; }
        public virtual DbSet<ShipAndDocking> ShipAndDockings { get; set; }
        public virtual DbSet<ShipDetail> ShipDetails { get; set; }
        public virtual DbSet<ShipInactive> ShipInactives { get; set; }
        public virtual DbSet<ShipInactiveOrg> ShipInactiveOrgs { get; set; }
        public virtual DbSet<ShipInfo> ShipInfoes { get; set; }
        public virtual DbSet<ShipMovement> ShipMovements { get; set; }
        public virtual DbSet<ShipPower> ShipPowers { get; set; }
        public virtual DbSet<ShipRepairInfo> ShipRepairInfoes { get; set; }
        public virtual DbSet<ShipSpeedTrial> ShipSpeedTrials { get; set; }
        public virtual DbSet<TrainingInfo> TrainingInfoes { get; set; }
        public virtual DbSet<UserLogInfo> UserLogInfoes { get; set; }
        public virtual DbSet<ZoneInfo> ZoneInfoes { get; set; }
        public virtual DbSet<ApprovedRefitDockingSchedule> ApprovedRefitDockingSchedules { get; set; }
        public virtual DbSet<BankInfo> BankInfoes { get; set; }
        public virtual DbSet<GetNotDoneMachinariesInfo> GetNotDoneMachinariesInfoes { get; set; }
        public virtual DbSet<MEInfo> MEInfoes { get; set; }
        public virtual DbSet<Org> Orgs { get; set; }
        public virtual DbSet<Orgnaization1> Orgnaization1 { get; set; }
        public virtual DbSet<ProcurementByDNE> ProcurementByDNEs { get; set; }
        public virtual DbSet<ShipcommOrgnaization> ShipcommOrgnaizations { get; set; }
        public virtual DbSet<ShipInactiveDescription> ShipInactiveDescriptions { get; set; }
        public virtual DbSet<ShipOrgnaization> ShipOrgnaizations { get; set; }
        public virtual DbSet<signal> signals { get; set; }
        public virtual DbSet<UpdateOPlState> UpdateOPlStates { get; set; }
        public virtual DbSet<UpdateOPlState1> UpdateOPlState1 { get; set; }
        public virtual DbSet<UserBankInfo> UserBankInfoes { get; set; }
        public virtual DbSet<vAccountInfo> vAccountInfoes { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<vwPontoon> vwPontoons { get; set; }
        public virtual DbSet<vwRefitDokingNotification> vwRefitDokingNotifications { get; set; }
        public virtual DbSet<vwShipBankInfo> vwShipBankInfoes { get; set; }
        public virtual DbSet<vwShipBranchInfo> vwShipBranchInfoes { get; set; }
        public virtual DbSet<vwUserProfile> vwUserProfiles { get; set; }
        public virtual DbSet<ReturnReportNo> ReturnReportNoes { get; set; }
        public virtual DbSet<ReturnReportYear> ReturnReportYears { get; set; }
        public virtual DbSet<QuaterlyMainEnginesGeneratorsRunningHour> QuaterlyMainEnginesGeneratorsRunningHours { get; set; }
        public virtual DbSet<AsAndAsInfo> AsAndAsInfoes { get; set; }
        public virtual DbSet<RefitDockingSchedule> RefitDockingSchedules { get; set; }
        public virtual DbSet<QuaterlyReturn> QuaterlyReturns { get; set; }
        public virtual DbSet<QuaterlyReturnEngineerOfficerRemark> QuaterlyReturnEngineerOfficerRemarks { get; set; }
        public virtual DbSet<ControlShipInfo> ControlShipInfoes { get; set; }
        public virtual DbSet<YearlyReturn> YearlyReturns { get; set; }
        public virtual DbSet<YearlyReturnDetail> YearlyReturnDetails { get; set; }
        public virtual DbSet<CommonCode> CommonCodes { get; set; }
        public virtual DbSet<ICE> ICE { get; set; }
        public virtual DbSet<UserURLRight> UserURLRights { get; set; }
        public virtual DbSet<MonthlyReturn> MonthlyReturns { get; set; }
        public virtual DbSet<RoleUserURLRightMapping> RoleUserURLRightMappings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<BranchInfo> BranchInfoes { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<MachineryInfo> MachineryInfoes { get; set; }
        public virtual DbSet<vwNotification> vwNotifications { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RefitDockingReportExcell> RefitDockingReportExcells { get; set; }
        public virtual DbSet<MessageInfo> MessageInfoes { get; set; }
    }
}
