//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class OilRate
    {
        public long OilRateId { get; set; }
        public Nullable<long> MonthlyReturnId { get; set; }
        public Nullable<int> OilNameId { get; set; }
        public Nullable<decimal> Expense { get; set; }
        public Nullable<decimal> PerLtRate { get; set; }
        public Nullable<decimal> TotalExpense { get; set; }
    }
}
