//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLExpenseInfo
    {
        public long POLExpenseInfoId { get; set; }
        public Nullable<long> MonthlyReturnId { get; set; }
        public Nullable<long> ShipId { get; set; }
        public Nullable<long> OilName { get; set; }
        public Nullable<decimal> InitialStockLtrOrUnit { get; set; }
        public Nullable<decimal> ReceivedQtyLtrorUnit { get; set; }
        public Nullable<decimal> HandoverLtrOrUnit { get; set; }
        public Nullable<decimal> MonthlyUseltrOrUnit { get; set; }
        public Nullable<decimal> StockAfterUseLtrOrUnit { get; set; }
        public Nullable<decimal> OilPerLtRate { get; set; }
    
        public virtual CommonCode CommonCode { get; set; }
        public virtual MonthlyReturn MonthlyReturn { get; set; }
    }
}
