//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuaterlyReturnEngineerOfficerRemark
    {
        public long QuaterlyReturnEngineerOfficerRemarkId { get; set; }
        public string RemarkTitle { get; set; }
        public string RemarkDetails { get; set; }
        public Nullable<long> QuaterlyReturnId { get; set; }
    
        public virtual QuaterlyReturn QuaterlyReturn { get; set; }
    }
}
