//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleUserURLRightMapping
    {
        public int RoleUserURLRightMappingId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<long> UserUrlRightsId { get; set; }
        public bool Visible { get; set; }
    }
}
