//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipPower
    {
        public long ShipPowerIdentity { get; set; }
        public long ShipId { get; set; }
        public string Description { get; set; }
        public decimal Speed { get; set; }
        public decimal Duration { get; set; }
        public decimal EnduranceHr { get; set; }
        public decimal EnduranceNm { get; set; }
        public decimal ShaftSpeed { get; set; }
        public decimal Power { get; set; }
        public decimal FuelConsumption { get; set; }
        public string UserId { get; set; }
        public System.DateTime Lastupdate { get; set; }
        public Nullable<long> ControlShipInfoId { get; set; }
    
        public virtual ControlShipInfo ControlShipInfo { get; set; }
    }
}
