//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipInactive
    {
        public long SInactiveIdentity { get; set; }
        public Nullable<long> MessageInfoIdentity { get; set; }
        public long ControlShipInfoIdentity { get; set; }
        public string MechineLevel2 { get; set; }
        public string MechineLevel3 { get; set; }
        public string CrashDetails { get; set; }
        public System.DateTime InactiveDate { get; set; }
        public string TakenStap { get; set; }
        public string Reference { get; set; }
        public Nullable<int> MachineryId { get; set; }
        public Nullable<long> ShipStatus { get; set; }
        public Nullable<bool> IsCompeleted { get; set; }
        public string UserID { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual ControlShipInfo ControlShipInfo { get; set; }
        public virtual CommonCode CommonCode { get; set; }
    }
}
