//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipRepairInfo
    {
        public long ShipRepairIdentity { get; set; }
        public long ShipInfoIdentity { get; set; }
        public string FinantialYear { get; set; }
        public System.DateTime DockingStart { get; set; }
        public System.DateTime DockingEnd { get; set; }
        public Nullable<decimal> RepairCost { get; set; }
        public string DockingPlace { get; set; }
        public string UserId { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual ControlShipInfo ControlShipInfo { get; set; }
    }
}
