//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateOPlState1
    {
        public Nullable<long> ParentCode { get; set; }
        public Nullable<decimal> id { get; set; }
        public Nullable<int> OPL { get; set; }
        public Nullable<int> NonOpl { get; set; }
        public Nullable<int> TotalShip { get; set; }
        public string Name { get; set; }
        public int LEVEL { get; set; }
        public int firstLevel { get; set; }
        public Nullable<long> SecendLevel { get; set; }
        public Nullable<decimal> ThirdLevel { get; set; }
    }
}
