//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBankInfo
    {
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string LoweredRoleName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserFullName { get; set; }
        public bool ApprovedUser { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> AttemptCount { get; set; }
        public Nullable<int> PasswordValidityInDays { get; set; }
        public Nullable<System.DateTime> LastPasswordChangeDate { get; set; }
        public bool IsLogin { get; set; }
        public string IPAddress { get; set; }
        public string HostName { get; set; }
        public string BankName { get; set; }
        public Nullable<long> BankCodeIdentity { get; set; }
        public Nullable<long> DistrictCodeIdentity { get; set; }
        public string DistrictName { get; set; }
        public long BranchInfoIdentity { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string PermanentAddress { get; set; }
        public string PresentAddress { get; set; }
        public string NationalId { get; set; }
        public Nullable<long> Designation { get; set; }
        public Nullable<long> Sex { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string PhotographUrl { get; set; }
        public string SignatureUrl { get; set; }
        public long UserId { get; set; }
        public string ShipName { get; set; }
        public long ControlShipInfoId { get; set; }
    }
}
