//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogInfo
    {
        public long SlNo { get; set; }
        public string LoginUserId { get; set; }
        public string Workstation { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public string Country { get; set; }
        public string Location { get; set; }
        public string Remarks { get; set; }
    }
}
