//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public Nullable<long> Organization { get; set; }
        public decimal ControlCode { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public int Expr2 { get; set; }
        public int Expr3 { get; set; }
        public Nullable<long> Expr4 { get; set; }
        public Nullable<decimal> Expr5 { get; set; }
    }
}
