//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwNotification
    {
        public string ShipName { get; set; }
        public string Machinery { get; set; }
        public string Model { get; set; }
        public long MachinariesInfoIdentity { get; set; }
        public Nullable<decimal> RunningHour { get; set; }
        public string UserFullName { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public long UserShipId { get; set; }
        public string UserShipName { get; set; }
        public string Code { get; set; }
        public string BankCode { get; set; }
        public string DistrictCode { get; set; }
        public string DistrictName { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
    }
}
