//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPontoon
    {
        public long ShipRepairIdentity { get; set; }
        public long ShipInfoIdentity { get; set; }
        public string FinantialYear { get; set; }
        public System.DateTime DockingStart { get; set; }
        public System.DateTime DockingEnd { get; set; }
        public Nullable<decimal> RepairCost { get; set; }
        public string DockingPlace { get; set; }
        public string UserId { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<long> rn { get; set; }
        public Nullable<long> ControlShipInfoId { get; set; }
        public Nullable<decimal> ParentCode { get; set; }
        public Nullable<decimal> ControlCode { get; set; }
        public string ControlName { get; set; }
        public string ControlValue { get; set; }
        public string AdditionalValue { get; set; }
        public string Sqdn { get; set; }
        public string ContactNo { get; set; }
        public Nullable<long> SQD { get; set; }
        public Nullable<long> Organization { get; set; }
        public Nullable<long> ShipType { get; set; }
        public Nullable<long> Status { get; set; }
        public string Remarks { get; set; }
        public string Authority { get; set; }
        public Nullable<int> ControlLevel { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Level1 { get; set; }
        public string Level2 { get; set; }
        public string Level3 { get; set; }
        public string Level4 { get; set; }
        public string Level5 { get; set; }
        public Nullable<System.DateTime> CommotionDate { get; set; }
        public string NickName { get; set; }
        public Nullable<long> ClassId { get; set; }
        public string ShipsPackFile { get; set; }
        public string DisplacementFullLoad { get; set; }
        public string DisplacementLightWeight { get; set; }
        public string Manufacturer { get; set; }
        public string LengthMTR { get; set; }
        public string DateOfCommission { get; set; }
        public string Breadth { get; set; }
        public string HeightOfMast { get; set; }
        public string DraftFwd { get; set; }
        public string Depth { get; set; }
        public string Depth1 { get; set; }
        public string DraftAft { get; set; }
        public string MaximumSpeed { get; set; }
        public string FreshWaterCapacity { get; set; }
        public string MaximumContinuousSpeed { get; set; }
        public string FualCapacity { get; set; }
        public string CruisingSpeed { get; set; }
        public string LuboilCapcity { get; set; }
        public string EconomicSpeed { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string LastUpdateId { get; set; }
        public Nullable<System.DateTime> CreateUserDate { get; set; }
        public string CreateUserId { get; set; }
    }
}
