//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRefitDokingNotification
    {
        public Nullable<long> SerialNo { get; set; }
        public long ControlShipInfoId { get; set; }
        public string ShipName { get; set; }
        public Nullable<System.DateTime> PNextRefitFrom { get; set; }
        public Nullable<System.DateTime> PNextDockingFrom { get; set; }
        public Nullable<System.DateTime> PNextRefitTo { get; set; }
        public Nullable<System.DateTime> PNextDockingTo { get; set; }
        public Nullable<int> NextRefitFromDay { get; set; }
        public Nullable<int> NextDokingFromDay { get; set; }
        public Nullable<int> NextRefitToDay { get; set; }
        public Nullable<int> NextDokingToDay { get; set; }
        public string NextRefitFromMsg { get; set; }
        public string NextDokingFromMsg { get; set; }
        public string NextRefitToMsg { get; set; }
        public string NextDokingToMsg { get; set; }
    }
}
