//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Model.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearlyReturn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YearlyReturn()
        {
            this.YearlyReturnDetails = new HashSet<YearlyReturnDetail>();
        }
    
        public long YearlyReturnId { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<long> DeskNoId { get; set; }
        public string FrameNo { get; set; }
        public Nullable<long> ShipId { get; set; }
        public Nullable<int> YearlyReturnType { get; set; }
    
        public virtual ControlShipInfo ControlShipInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YearlyReturnDetail> YearlyReturnDetails { get; set; }
        public virtual CommonCode CommonCode { get; set; }
    }
}
